service: tools-serverless
app: vitafit-tools
tenant: ethan605
provider:
  name: aws
  runtime: nodejs10.x
  profile: vitafit-serverless
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: sendEmail
          method: post
          request:
          parameters:
            appended_text: false
            html_body: true
            subject: true
            to_address: true