service: tools-serverless
provider:
  name: aws
  runtime: nodejs10.x
  profile: vitafit-serverless
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"
functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: sendEmail
          method: post